Update action.yml

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -26,4 +26,7 @@ runs:
         if echo "$BODY_LOWER" | grep -q "$MARKED"; then
           echo "Checkbox is checked"
           exit 0
+        else
+          echo "Checkbox not found in pull request description"
+          exit 1
       shell: bash
