Update action.yml

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -20,11 +20,17 @@ runs:
         CHECKBOX: ${{ inputs.checkbox }}
       run: |
         set -x
+        CHECKED="\[x\] $CHECKBOX"
         UNCHECKED="\[ \] $CHECKBOX"
-        MARKED="\[x\] $CHECKBOX"
         BODY_LOWER=$(echo "$BODY" | tr '[:upper:]' '[:lower:]')
-        if [[ "$BODY_LOWER" =~ "$MARKED" ]]; then
+        if [[ "$BODY_LOWER" =~ "$CHECKED" ]]; then
           echo "Checkbox is checked"
           exit 0
+        elif [[ "$BODY_LOWER" =~ "$UNCHECKED" ]]; then
+          echo "Checkbox is NOT checked"
+          exit 1
+        else
+          echo "Checkbox not found in pull request description"
+          exit 1
         fi
       shell: bash
